SLURM_NODELIST=""
SLURM_ENABLED="auto"
SLURM_PARTITION=""
SLURM_ACCOUNT=""
SLURM_QOS=""
SLURM_TIME="72:00:00"
SLURM_CPUS_PER_SAMPLE="16"
SLURM_MEM_PER_SAMPLE="76G"
SLURM_MAX_ARRAY_TASKS="2"
SLURM_EXCLUSIVE="0"
SLURM_EXCLUDE=""
SLURM_EXTRA_ARGS=""
SLURM_FINALIZE_CPUS="4"
SLURM_FINALIZE_MEM="32G"
SLURM_FINALIZE_TIME="12:00:00"
