#!/usr/bin/env bash
# shellcheck shell=bash

ENDO_EXO_VERSION="3.0.0"
ENDO_EXO_SCRIPT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_DIR="${PROJECT_DIR:-$(cd "${ENDO_EXO_SCRIPT_ROOT}/.." && pwd)}"
PIPELINE_CONFIG="${PIPELINE_CONFIG:-${PROJECT_DIR}/config/pipeline.conf}"
SLURM_CONFIG="${SLURM_CONFIG:-${PROJECT_DIR}/config/slurm.conf}"

if [[ -s "$PIPELINE_CONFIG" ]]; then
  # shellcheck disable=SC1090
  source "$PIPELINE_CONFIG"
fi

resolve_dir() {
  local configured="$1" fallback="$2"
  if [[ -n "$configured" ]]; then
    if [[ "$configured" = /* ]]; then
      printf '%s\n' "$configured"
    else
      printf '%s\n' "${PROJECT_DIR}/${configured}"
    fi
  else
    printf '%s\n' "$fallback"
  fi
}

DATA_DIR="$(resolve_dir "${ENDO_EXO_DATA_DIR:-}" "${PROJECT_DIR}/1.Data")"
RESULTS_DIR="$(resolve_dir "${ENDO_EXO_RESULTS_DIR:-}" "${PROJECT_DIR}/2.Results")"
REFS_DIR="$(resolve_dir "${ENDO_EXO_REFS_DIR:-}" "${PROJECT_DIR}/3.Refs")"
LOGS_DIR="$(resolve_dir "${ENDO_EXO_LOGS_DIR:-}" "${PROJECT_DIR}/_Logs")"

ENDO_EXO_CORE_IMAGE="${ENDO_EXO_CORE_IMAGE:-endo-exo/core:${ENDO_EXO_VERSION}}"
ENDO_EXO_TELESCOPE_IMAGE="${ENDO_EXO_TELESCOPE_IMAGE:-endo-exo/telescope:${ENDO_EXO_VERSION}}"

export PROJECT_DIR PIPELINE_CONFIG SLURM_CONFIG DATA_DIR RESULTS_DIR REFS_DIR LOGS_DIR
export ENDO_EXO_VERSION ENDO_EXO_CORE_IMAGE ENDO_EXO_TELESCOPE_IMAGE
export DEFAULT_EXECUTOR="${DEFAULT_EXECUTOR:-auto}"
export THREADS="${THREADS:-16}" LOCAL_JOBS="${LOCAL_JOBS:-1}"
export TELESCOPE_THREADS="${TELESCOPE_THREADS:-8}" TELESCOPE_JOBS="${TELESCOPE_JOBS:-1}" TELESCOPE_USE_DOCKER="${TELESCOPE_USE_DOCKER:-1}"
export ENABLE_HPV="${ENABLE_HPV:-1}" ENABLE_HERV="${ENABLE_HERV:-1}" ENABLE_TE="${ENABLE_TE:-1}"
export ENABLE_TELESCOPE="${ENABLE_TELESCOPE:-1}" ENABLE_HUMAN_GENE_EXPRESSION="${ENABLE_HUMAN_GENE_EXPRESSION:-1}"
export FASTP_MODE="${FASTP_MODE:-skip}" FASTP_TIMEOUT_SECONDS="${FASTP_TIMEOUT_SECONDS:-3600}"
export FASTP_FALLBACK_TO_RAW="${FASTP_FALLBACK_TO_RAW:-0}" FASTP_DETECT_ADAPTER="${FASTP_DETECT_ADAPTER:-0}"
export HEAVY_FILES_POLICY="${HEAVY_FILES_POLICY:-keep}" INPUT_CHECKSUM_MODE="${INPUT_CHECKSUM_MODE:-metadata}" BUILD_LOCUS_SPARSE_MATRICES="${BUILD_LOCUS_SPARSE_MATRICES:-1}"
export STAR_MIN_MEM_KB="${STAR_MIN_MEM_KB:-30000000}" STAR_WAIT_SEC="${STAR_WAIT_SEC:-60}"
export GENE_FEATURECOUNTS_STRAND="${GENE_FEATURECOUNTS_STRAND:-0}"
export GENE_FEATURECOUNTS_MIN_MAPQ="${GENE_FEATURECOUNTS_MIN_MAPQ:-10}"

mkdir -p "$DATA_DIR" "$RESULTS_DIR" "$REFS_DIR" "$LOGS_DIR"
